# Generated by Django 5.2.15 on 2026-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='energy',
            field=models.FloatField(default=0),
        ),
    ]
